version: '3'
services:
  database:
    image: 'postgres:12'
    restart: always
    container_name: 'postgresql-service'
    environment:
      - 'POSTGRES_USER=absence_manager_api'
      - 'POSTGRES_PASSWORD=secret'
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/var/lib/postgresql/test/data

  api:
    image: absence-manager-api
    entrypoint: [entrypoints/api-entrypoint.sh]
    build:
      context: .
      args:
        GIT_BRANCH: master
    # WARN: Comment volumes lines only if you change GIT_BRANCH defaul value
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env.docker

volumes:
  postgresql_data:
    driver: local
