name: Docker Compose CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run docker compose
        run: docker-compose up -d

      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          docker-compose run api rails db:test:prepare
          docker-compose run api rails test
